In [1]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/

In [4]:
!kaggle datasets download -d paramaggarwal/fashion-product-images-small


 98% 555M/565M [00:04<00:00, 146MB/s]
100% 565M/565M [00:04<00:00, 124MB/s]


In [5]:
import zipfile
zip_ref = zipfile.ZipFile('/content/fashion-product-images-small.zip', 'r')
zip_ref.extractall('/content')
zip_ref.close()

In [23]:
import tensorflow
from keras.preprocessing import image
from keras.layers import  GlobalMaxPooling2D
from keras.applications.resnet50 import ResNet50
import numpy as np
from keras.applications.resnet50 import preprocess_input


In [7]:
model=ResNet50(weights="imagenet",include_top=False,input_shape=(224,224,3))
model.trainable=False

94765736/94765736 [==============================] - 1s 0us/step


In [8]:
model=tensorflow.keras.Sequential([
    model,
    GlobalMaxPooling2D()

])

In [9]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 resnet50 (Functional)       (None, 7, 7, 2048)        23587712  
                                                                 
 global_max_pooling2d (Glob  (None, 2048)              0         
 alMaxPooling2D)                                                 
                                                                 
Total params: 23587712 (89.98 MB)
Trainable params: 0 (0.00 Byte)
Non-trainable params: 23587712 (89.98 MB)
_________________________________________________________________


In [13]:
img=image.load_img("/content/myntradataset/images/10000.jpg",target_size=(224,224))

In [17]:
img_array=image.img_to_array(img)

In [18]:
img_array.shape

(224, 224, 3)

In [19]:
expand_img_array=np.expand_dims(img_array,axis=0)

In [26]:
expand_img_array.shape

(1, 224, 224, 3)

In [20]:
expand_img_array

array([[[[255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.],
         ...,
         [255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.]],

        [[255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.],
         ...,
         [255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.]],

        [[255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.],
         ...,
         [255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.]],

        ...,

        [[255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.],
         ...,
         [255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.]],

        [[255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.],
         ...,
         [255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.]],

        [[255., 255., 255.],
       

In [24]:
preprocessed_img=preprocess_input(expand_img_array)

In [25]:
preprocessed_img

array([[[[151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ],
         ...,
         [151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ]],

        [[151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ],
         ...,
         [151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ]],

        [[151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ],
         ...,
         [151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ]],

        ...,

        [[151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ],
         [151.061  , 138.22101, 131.32   ],
         ...,


In [28]:
model.predict(preprocessed_img).shape

1/1 [==============================] - 0s 243ms/step


(1, 2048)

In [29]:
model.predict(preprocessed_img).flatten().shape

1/1 [==============================] - 0s 22ms/step


(2048,)

In [30]:
from numpy.linalg import norm
norm(model.predict(preprocessed_img))

1/1 [==============================] - 0s 23ms/step


254.24016

In [31]:
model.predict(preprocessed_img).flatten()/norm(model.predict(preprocessed_img).flatten())

1/1 [==============================] - 0s 21ms/step


array([0.        , 0.01761623, 0.00171607, ..., 0.0124722 , 0.02726392,
       0.06899212], dtype=float32)

In [32]:
def extract_feature(img_path,model):
  img=image.load_img(img_path,target_size=(224,224))
  img_array=image.img_to_array(img)
  expand_img_array=np.expand_dims(img_array,axis=0)
  preprocessed_img=preprocess_input(expand_img_array)
  result=model.predict(preprocessed_img).flatten()
  normalized_result=result/norm(result)

  return normalized_result




In [33]:
import os

In [37]:
filenames=[]
for file in os.listdir("/content/myntradataset/images"):
  filenames.append(os.path.join("images",file))



In [41]:
len(filenames)

44441

In [42]:
print(filenames[0:5])

['images/31185.jpg', 'images/11222.jpg', 'images/17321.jpg', 'images/29225.jpg', 'images/33585.jpg']


In [43]:
feature_list=[]
for file in filenames:
  feature_list.append(extract_feature(file,model))



Streaming output truncated to the last 5000 lines.
1/1 [==============================] - 0s 40ms/step


In [ ]:
print(np.array(feature_list).shape)

In [44]:
import pickle
pickle.dump(feature_list,open("embedding.pkl","wb"))
pickle.dump(filenames,open("filenames.pkl","wb"))